[package]
name = "zk-fedeval-prover"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
burn = { version = "0.21.0", features = ["ndarray"] }
burn-store = { version = "0.21.0" }
ndarray = "0.17.2"
ndarray-npy = "0.10.0"
anyhow = "1"

[build-dependencies]
burn-import = { version = "0.21.0", features = ["onnx"] }